/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Penggunaan',
      items: [{type: 'autogenerated', dirName: 'penggunaan'}],
    },
    {
      type: 'category',
      label: 'Referensi',
      items: [{type: 'autogenerated', dirName: 'referensi'}],
    },
  ],
};

export default sidebars;
