/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'About',
      collapsible: false,
      link: {
        type: 'doc',
        id: 'about/main',
      },
      items: [{type: 'autogenerated', dirName: 'about'}],
    },
    {
      type: 'category',
      label: 'Use Cases',
      collapsible: false,
      link: {
        type: 'doc',
        id: 'usecase/main',
      },
      items: [{type: 'autogenerated', dirName: 'usecase'}],
    },
    {
      type: 'category',
      label: 'Services',
      collapsible: false,
      link: {
        type: 'doc',
        id: 'services/main',
      },
      items: [{type: 'autogenerated', dirName: 'services'}],
    },
  ],
};

export default sidebars;
